name: K6 Load Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: load-test.js
        env:
          K6_PROMETHEUS_RW_SERVER_URL: ${{ secrets.GRAFANA_URL }}
          K6_PROMETHEUS_RW_USERNAME: ${{ secrets.GRAFANA_USER }}
          K6_PROMETHEUS_RW_PASSWORD: ${{ secrets.GRAFANA_API_KEY }}
          K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM: "true"
